"use strict";
const C = Object.freeze({TABLE_COUNT:15,REQUEST_COOLDOWN_MS:300000,SEARCH_LIMIT:8,MAX_QUEUE_SIZE:70,RESTAURANT_ID:"demo-restaurant",DEMO_DJ_PIN:"1234",DEMO_ADMIN_PIN:"9999",...(window.BEATBITES_CONFIG||{})});
const K={TABLES:"bb3_tables",GUESTS:"bb3_guests",SESSIONS:"bb3_sessions",QUEUE:"bb3_queue",VOTES:"bb3_votes",PLAYING:"bb3_playing",COOLDOWNS:"bb3_cooldowns",DJ:"bb3_dj",ADMIN:"bb3_admin",ACTIVE_SESSION:"bb3_active_session"};
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const dbOn=Boolean(C.SUPABASE_URL&&C.SUPABASE_ANON_KEY&&window.supabase); const sb=dbOn?window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
const local={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v));window.dispatchEvent(new Event("bb3-local"))}};
const uid=()=>crypto.randomUUID(); const now=()=>Date.now(); const fmt=ms=>{let s=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`};
const debounce=(fn,w=350)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),w)}};
function seedDemoTables(){let t=local.get(K.TABLES,null); if(t) return t; t=Array.from({length:C.TABLE_COUNT},(_,i)=>({id:uid(),restaurant_id:C.RESTAURANT_ID,table_number:i+1,access_token:`demo-table-${i+1}`,active:true})); local.set(K.TABLES,t); return t;}
seedDemoTables();
const api={
 async findTableByToken(token){token=String(token||"").trim(); if(!token) return null; if(!dbOn) return local.get(K.TABLES,[]).find(t=>t.access_token===token&&t.active)||null; const {data,error}=await sb.from("restaurant_tables").select("*").eq("restaurant_id",C.RESTAURANT_ID).eq("access_token",token).eq("active",true).single(); if(error) return null; return data;},
 async upsertGuest(g){ if(!dbOn){let guests=local.get(K.GUESTS,[]); let existing=guests.find(x=>x.mobile===g.mobile); if(existing){existing={...existing,...g,visit_count:(existing.visit_count||1)+1,last_visit_at:new Date().toISOString()}; guests=guests.map(x=>x.id===existing.id?existing:x); local.set(K.GUESTS,guests); return existing;} const ng={id:uid(),...g,visit_count:1,created_at:new Date().toISOString(),last_visit_at:new Date().toISOString()}; guests.push(ng); local.set(K.GUESTS,guests); return ng;} const {data,error}=await sb.from("guests").upsert(g,{onConflict:"restaurant_id,mobile"}).select().single(); if(error) throw error; return data;},
 async createSession(guest,table){const sess={id:uid(),restaurant_id:C.RESTAURANT_ID,guest_id:guest.id,table_id:table.id,table_number:table.table_number,created_at:new Date().toISOString(),expires_at:new Date(Date.now()+4*60*60*1000).toISOString()}; if(!dbOn){let s=local.get(K.SESSIONS,[]);s.push(sess);local.set(K.SESSIONS,s);return sess;} const {data,error}=await sb.from("guest_sessions").insert(sess).select().single(); if(error) throw error; return data;},
 async getQueue(){ if(!dbOn) return local.get(K.QUEUE,[]).sort(scoreSort); const {data,error}=await sb.from("song_requests_view").select("*").eq("restaurant_id",C.RESTAURANT_ID).eq("status","queued"); if(error) throw error; return data.map(mapReq).sort(scoreSort);},
 async addRequest(song){ if(!dbOn){let q=local.get(K.QUEUE,[]);q.push(song);local.set(K.QUEUE,q);return song;} const {data,error}=await sb.from("song_requests").insert(toReqRow(song)).select().single(); if(error) throw error; return mapReq(data);},
 async vote(requestId,session){ if(!dbOn){let votes=local.get(K.VOTES,[]); if(votes.some(v=>v.request_id===requestId&&v.session_id===session.id)) throw new Error("already voted"); votes.push({id:uid(),request_id:requestId,session_id:session.id,guest_id:session.guest_id,created_at:new Date().toISOString()}); local.set(K.VOTES,votes); let q=local.get(K.QUEUE,[]).map(x=>x.id===requestId?{...x,votes:(x.votes||0)+1}:x); local.set(K.QUEUE,q); return true;} const {error}=await sb.from("song_votes").insert({id:uid(),restaurant_id:C.RESTAURANT_ID,request_id:requestId,session_id:session.id,guest_id:session.guest_id}); if(error) throw error; return true;},
 async remove(id,status="removed"){ if(!dbOn){local.set(K.QUEUE,local.get(K.QUEUE,[]).filter(x=>x.id!==id));return;} const {error}=await sb.from("song_requests").update({status}).eq("id",id); if(error) throw error;},
 async playNext(){const q=await this.getQueue(); if(!q.length) return null; const next=q[0]; if(!dbOn){local.set(K.QUEUE,local.get(K.QUEUE,[]).filter(x=>x.id!==next.id)); local.set(K.PLAYING,next); return next;} const {error}=await sb.from("song_requests").update({status:"playing",played_at:new Date().toISOString()}).eq("id",next.id); if(error) throw error; local.set(K.PLAYING,next); return next;},
 async clearQueue(){ if(!dbOn){local.set(K.QUEUE,[]);return;} const {error}=await sb.from("song_requests").update({status:"removed"}).eq("restaurant_id",C.RESTAURANT_ID).eq("status","queued"); if(error) throw error;},
 getGuests(){return local.get(K.GUESTS,[])}, getPlaying(){return local.get(K.PLAYING,null)}, clearPlaying(){local.set(K.PLAYING,null)}
};
function scoreSort(a,b){return ((b.votes||0)*10+b.requested_at)-((a.votes||0)*10+a.requested_at)}
function mapReq(r){return {id:r.id,restaurant_id:r.restaurant_id,title:r.title,artist:r.artist,artwork_url:r.artwork_url,preview_url:r.preview_url,table_number:r.table_number,guest_id:r.guest_id,session_id:r.session_id,status:r.status,requested_at:new Date(r.requested_at).getTime(),votes:Number(r.votes||0)}}
function toReqRow(s){return {id:s.id,restaurant_id:s.restaurant_id,title:s.title,artist:s.artist,artwork_url:s.artwork_url,preview_url:s.preview_url,table_number:s.table_number,guest_id:s.guest_id,session_id:s.session_id,status:"queued",requested_at:new Date(s.requested_at).toISOString()}}
const app={state:{table:null,guest:null,session:null,queue:[],searchAbort:null,cooldownTimer:null},
 init(){this.bind();this.fromUrl();this.qrs();this.realtime();this.renderAll();},
 bind(){ $$('[data-view]').forEach(b=>b.addEventListener('click',()=>this.nav(b.dataset.view))); $('#adminLink').addEventListener('click',()=>this.nav('admin-login')); $('#tokenForm').addEventListener('submit',e=>{e.preventDefault();this.validateToken($('#tableTokenInput').value)}); $('#guestForm').addEventListener('submit',e=>{e.preventDefault();this.registerGuest()}); $('#songSearch').addEventListener('input',debounce(e=>this.searchSong(e.target.value))); $('#refreshCustomerQueue').addEventListener('click',()=>this.renderAll()); $('#djLoginForm').addEventListener('submit',e=>{e.preventDefault();this.djLogin()}); $('#adminLoginForm').addEventListener('submit',e=>{e.preventDefault();this.adminLogin()}); $('#playNext').addEventListener('click',()=>this.playNext()); $('#clearNow').addEventListener('click',()=>{api.clearPlaying();this.toast('Now playing cleared');this.renderAll()}); $('#clearQueue').addEventListener('click',()=>this.clearQueue()); $('#djFilter').addEventListener('input',()=>this.renderDJ()); window.addEventListener('storage',()=>this.renderAll()); window.addEventListener('bb3-local',()=>this.renderAll()); document.addEventListener('click',e=>{if(!e.target.closest('.search-card'))$('#suggestions').style.display='none'});},
 nav(v){$$('.view').forEach(x=>x.classList.remove('active')); $(`#view-${v}`).classList.add('active'); if(v==='customer') this.cooldown(); this.renderAll();},
 fromUrl(){const token=new URLSearchParams(location.search).get('t'); if(token) this.validateToken(token);},
 async validateToken(token){const table=await api.findTableByToken(token); if(!table) return this.toast('Invalid or inactive table QR token','error'); this.state.table=table; $('#activeTablePill').textContent=`Table ${table.table_number}`; this.nav('guest-registration');},
 async registerGuest(){if(!this.state.table)return this.toast('Table token required','error'); const mobile=$('#guestMobile').value.trim(); if(!/^\+?[0-9\s-]{8,15}$/.test(mobile)) return this.toast('Enter a valid mobile number','error'); if(!$('#guestConsent').checked) return this.toast('Consent is required','error'); const guest=await api.upsertGuest({restaurant_id:C.RESTAURANT_ID,name:$('#guestName').value.trim(),mobile,email:$('#guestEmail').value.trim()||null,dob:$('#guestDob').value||null,favorite_genre:$('#guestGenre').value||null}); const session=await api.createSession(guest,this.state.table); this.state.guest=guest; this.state.session=session; localStorage.setItem(K.ACTIVE_SESSION,JSON.stringify({guest,session,table:this.state.table})); $('#guestWelcome').textContent=`Welcome, ${guest.name}`; this.toast('Guest session created'); this.nav('customer');},
 async searchSong(q){q=q.trim(); const box=$('#suggestions'); if(q.length<2){box.style.display='none';return} if(this.state.searchAbort)this.state.searchAbort.abort(); this.state.searchAbort=new AbortController(); box.textContent=''; box.append(this.msg('Searching...')); box.style.display='block'; try{const res=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(q)}&media=music&entity=song&limit=${C.SEARCH_LIMIT}`,{signal:this.state.searchAbort.signal}); const json=await res.json(); box.textContent=''; const songs=(json.results||[]).filter(s=>s.trackName&&s.artistName); if(!songs.length) box.append(this.msg('No songs found')); songs.forEach(s=>box.append(this.songButton(s)));}catch(e){if(e.name!=='AbortError'){box.textContent='';box.append(this.msg('Search failed. Check internet.'))}}},
 msg(t){const d=document.createElement('div');d.className='suggestion';d.textContent=t;return d},
 songButton(s){const b=document.createElement('button');b.type='button';b.className='suggestion'; const img=document.createElement('img');img.className='cover';img.alt='Album cover';img.src=s.artworkUrl100||''; const div=document.createElement('div'); const title=document.createElement('div');title.className='title';title.textContent=s.trackName; const meta=document.createElement('div');meta.className='meta';meta.textContent=s.artistName; div.append(title,meta); b.append(img,div); b.addEventListener('click',()=>this.addSong(s)); return b},
 async addSong(raw){if(!this.state.session)return this.toast('Guest session required','error'); const cds=local.get(K.COOLDOWNS,{}); const last=Number(cds[this.state.session.id]||0); if(now()-last<C.REQUEST_COOLDOWN_MS){this.cooldown();return this.toast('Cooldown active','error')} const q=await api.getQueue(); if(q.length>=C.MAX_QUEUE_SIZE)return this.toast('Queue is full','error'); if(q.some(x=>x.title.toLowerCase()===raw.trackName.toLowerCase()&&x.artist.toLowerCase()===raw.artistName.toLowerCase()))return this.toast('Song already queued','error'); const song={id:uid(),restaurant_id:C.RESTAURANT_ID,title:raw.trackName,artist:raw.artistName,artwork_url:raw.artworkUrl100||'',preview_url:raw.previewUrl||'',table_number:this.state.session.table_number,guest_id:this.state.guest.id,session_id:this.state.session.id,status:'queued',requested_at:now(),votes:0}; await api.addRequest(song); cds[this.state.session.id]=now(); local.set(K.COOLDOWNS,cds); $('#songSearch').value=''; $('#suggestions').style.display='none'; $('#myRequestBox').classList.remove('hidden'); $('#myRequestBox').textContent=`Request added: ${song.title} - ${song.artist}`; this.toast('Song requested'); this.cooldown(); this.renderAll();},
 cooldown(){if(this.state.cooldownTimer)clearInterval(this.state.cooldownTimer); const box=$('#cooldownBox'), time=$('#cooldownTime'), input=$('#songSearch'); const update=()=>{const sid=this.state.session?.id; const last=Number(local.get(K.COOLDOWNS,{})[sid]||0); const left=C.REQUEST_COOLDOWN_MS-(now()-last); if(left>0){box.classList.remove('hidden');input.disabled=true;time.textContent=fmt(left)}else{box.classList.add('hidden');input.disabled=false;clearInterval(this.state.cooldownTimer);this.state.cooldownTimer=null}}; update(); this.state.cooldownTimer=setInterval(update,1000)},
 async vote(id){if(!this.state.session)return this.toast('Guest session required','error'); try{await api.vote(id,this.state.session);this.toast('Vote added');this.renderAll()}catch{this.toast('You already voted for this request','error')}},
 djLogin(){if($('#djPin').value.trim()===C.DEMO_DJ_PIN){sessionStorage.setItem(K.DJ,'1');this.nav('dj')}else this.toast('Wrong DJ PIN','error')},
 adminLogin(){if($('#adminPin').value.trim()===C.DEMO_ADMIN_PIN){sessionStorage.setItem(K.ADMIN,'1');this.nav('admin')}else this.toast('Wrong Admin PIN','error')},
 async playNext(){if(!sessionStorage.getItem(K.DJ))return this.toast('DJ login required','error'); const n=await api.playNext(); if(!n)return this.toast('Queue empty','error'); this.toast(`Playing: ${n.title}`); this.renderAll()},
 async clearQueue(){if(!sessionStorage.getItem(K.ADMIN))return this.toast('Admin login required','error'); if(confirm('Clear all queued songs?')){await api.clearQueue();this.toast('Queue cleared');this.renderAll()}},
 async remove(id){if(!sessionStorage.getItem(K.ADMIN))return this.toast('Admin login required','error'); await api.remove(id); this.toast('Removed'); this.renderAll()},
 async renderAll(){try{this.state.queue=await api.getQueue()}catch{this.state.queue=local.get(K.QUEUE,[])} this.renderCustomer();this.renderDJ();this.renderAdmin();this.renderStats();},
 renderCustomer(){this.renderQueue($('#customerQueue'),$('#customerEmpty'),this.state.queue,true,false)},
 renderDJ(){let f=($('#djFilter')?.value||'').toLowerCase(); let q=this.state.queue.filter(x=>`${x.title} ${x.artist} ${x.table_number}`.toLowerCase().includes(f)); this.renderQueue($('#djQueue'),$('#djEmpty'),q,false,false); const p=api.getPlaying(); $('#nowTitle').textContent=p?p.title:'Nothing playing'; $('#nowArtist').textContent=p?p.artist:'Queue ready'},
 renderAdmin(){this.renderQueue(null,null,[],false,true); const guests=api.getGuests(); const gl=$('#guestList'); if(!gl)return; gl.textContent=''; guests.slice(-8).reverse().forEach(g=>{const li=document.createElement('li');li.textContent=`${g.name} • ${g.mobile} • Visits: ${g.visit_count||1}`;gl.append(li)});},
 renderQueue(root,empty,items,customer=false,admin=false){if(!root)return; root.textContent=''; items.forEach((s,i)=>root.append(this.item(s,i+1,customer,admin))); if(empty)empty.style.display=items.length?'none':'block'},
 item(s,i,customer,admin){const li=document.createElement('li');li.className='queue-item';const main=document.createElement('div');main.className='queue-main';const img=document.createElement('img');img.className='cover';img.alt='Album cover';img.src=s.artwork_url||'';const info=document.createElement('div');const title=document.createElement('div');title.className='title';title.textContent=`${i}. ${s.title}`;const meta=document.createElement('div');meta.className='meta';meta.textContent=`${s.artist} • Table ${s.table_number} • Votes ${s.votes||0}`;info.append(title,meta);main.append(img,info);const actions=document.createElement('div');actions.className='queue-actions';const badge=document.createElement('span');badge.className='badge';badge.textContent=`#${i}`;actions.append(badge); if(customer){const v=document.createElement('button');v.className='btn btn-outline small';v.textContent='Vote';v.addEventListener('click',()=>this.vote(s.id));actions.append(v)} if(admin){const r=document.createElement('button');r.className='btn btn-danger small';r.textContent='Remove';r.addEventListener('click',()=>this.remove(s.id));actions.append(r)} li.append(main,actions);return li},
 renderStats(){const guests=api.getGuests(); const q=this.state.queue; const votes=q.reduce((a,b)=>a+(b.votes||0),0); ['statGuests','adminGuests'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=guests.length}); $('#statQueued')&&($('#statQueued').textContent=q.length); $('#statVotes')&&($('#statVotes').textContent=votes); $('#adminRequests')&&($('#adminRequests').textContent=q.length); $('#adminReturning')&&($('#adminReturning').textContent=guests.filter(g=>(g.visit_count||1)>1).length)},
 qrs(){const grid=$('#qrGrid'); if(!grid)return; grid.textContent=''; const origin=location.origin+location.pathname; seedDemoTables().forEach(t=>{const card=document.createElement('div');card.className='qr-card';const img=document.createElement('img');img.alt=`QR table ${t.table_number}`;img.src=`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(origin+'?t='+t.access_token)}`;const label=document.createElement('b');label.textContent=`Table ${t.table_number}`;const small=document.createElement('small');small.textContent=t.access_token;card.append(img,label,small);grid.append(card)})},
 realtime(){if(!dbOn)return; sb.channel('beatbites-live').on('postgres_changes',{event:'*',schema:'public',table:'song_requests'},()=>this.renderAll()).on('postgres_changes',{event:'*',schema:'public',table:'song_votes'},()=>this.renderAll()).subscribe()},
 toast(m,type='success'){const t=$('#toast');t.textContent=m;t.style.background=type==='error'?'var(--danger)':'var(--success)';t.style.color=type==='error'?'#fff':'#042117';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
}; document.addEventListener('DOMContentLoaded',()=>app.init());
